# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/admin/Documents/gui_zmey.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 879)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stepBox = QtWidgets.QGroupBox(self.centralwidget)
        self.stepBox.setGeometry(QtCore.QRect(20, 10, 191, 811))
        self.stepBox.setObjectName("stepBox")
        self.layoutWidget = QtWidgets.QWidget(self.stepBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 776))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stepButton_001 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_001.sizePolicy().hasHeightForWidth())
        self.stepButton_001.setSizePolicy(sizePolicy)
        self.stepButton_001.setAutoFillBackground(False)
        self.stepButton_001.setCheckable(False)
        self.stepButton_001.setChecked(False)
        self.stepButton_001.setAutoDefault(False)
        self.stepButton_001.setDefault(False)
        self.stepButton_001.setFlat(False)
        self.stepButton_001.setObjectName("stepButton_001")
        self.verticalLayout.addWidget(self.stepButton_001)
        self.stepButton_101 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_101.sizePolicy().hasHeightForWidth())
        self.stepButton_101.setSizePolicy(sizePolicy)
        self.stepButton_101.setAutoFillBackground(False)
        self.stepButton_101.setCheckable(False)
        self.stepButton_101.setChecked(False)
        self.stepButton_101.setAutoDefault(False)
        self.stepButton_101.setDefault(False)
        self.stepButton_101.setFlat(False)
        self.stepButton_101.setObjectName("stepButton_101")
        self.verticalLayout.addWidget(self.stepButton_101)
        self.stepButton_102 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_102.sizePolicy().hasHeightForWidth())
        self.stepButton_102.setSizePolicy(sizePolicy)
        self.stepButton_102.setObjectName("stepButton_102")
        self.verticalLayout.addWidget(self.stepButton_102)
        self.stepButton_103 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_103.sizePolicy().hasHeightForWidth())
        self.stepButton_103.setSizePolicy(sizePolicy)
        self.stepButton_103.setObjectName("stepButton_103")
        self.verticalLayout.addWidget(self.stepButton_103)
        self.stepButton_104 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_104.sizePolicy().hasHeightForWidth())
        self.stepButton_104.setSizePolicy(sizePolicy)
        self.stepButton_104.setObjectName("stepButton_104")
        self.verticalLayout.addWidget(self.stepButton_104)
        self.stepButton_105 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_105.sizePolicy().hasHeightForWidth())
        self.stepButton_105.setSizePolicy(sizePolicy)
        self.stepButton_105.setObjectName("stepButton_105")
        self.verticalLayout.addWidget(self.stepButton_105)
        self.stepButton_106 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_106.sizePolicy().hasHeightForWidth())
        self.stepButton_106.setSizePolicy(sizePolicy)
        self.stepButton_106.setObjectName("stepButton_106")
        self.verticalLayout.addWidget(self.stepButton_106)
        self.stepButton_107 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_107.sizePolicy().hasHeightForWidth())
        self.stepButton_107.setSizePolicy(sizePolicy)
        self.stepButton_107.setObjectName("stepButton_107")
        self.verticalLayout.addWidget(self.stepButton_107)
        self.stepButton_108 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_108.sizePolicy().hasHeightForWidth())
        self.stepButton_108.setSizePolicy(sizePolicy)
        self.stepButton_108.setObjectName("stepButton_108")
        self.verticalLayout.addWidget(self.stepButton_108)
        self.stepButton_109 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_109.sizePolicy().hasHeightForWidth())
        self.stepButton_109.setSizePolicy(sizePolicy)
        self.stepButton_109.setObjectName("stepButton_109")
        self.verticalLayout.addWidget(self.stepButton_109)
        self.stepButton_110 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_110.sizePolicy().hasHeightForWidth())
        self.stepButton_110.setSizePolicy(sizePolicy)
        self.stepButton_110.setObjectName("stepButton_110")
        self.verticalLayout.addWidget(self.stepButton_110)
        self.stepButton_111 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_111.sizePolicy().hasHeightForWidth())
        self.stepButton_111.setSizePolicy(sizePolicy)
        self.stepButton_111.setObjectName("stepButton_111")
        self.verticalLayout.addWidget(self.stepButton_111)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.stepButton_201 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_201.sizePolicy().hasHeightForWidth())
        self.stepButton_201.setSizePolicy(sizePolicy)
        self.stepButton_201.setObjectName("stepButton_201")
        self.verticalLayout.addWidget(self.stepButton_201)
        self.stepButton_202 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_202.sizePolicy().hasHeightForWidth())
        self.stepButton_202.setSizePolicy(sizePolicy)
        self.stepButton_202.setObjectName("stepButton_202")
        self.verticalLayout.addWidget(self.stepButton_202)
        self.stepButton_203 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_203.sizePolicy().hasHeightForWidth())
        self.stepButton_203.setSizePolicy(sizePolicy)
        self.stepButton_203.setObjectName("stepButton_203")
        self.verticalLayout.addWidget(self.stepButton_203)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.stepButton_301 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_301.sizePolicy().hasHeightForWidth())
        self.stepButton_301.setSizePolicy(sizePolicy)
        self.stepButton_301.setObjectName("stepButton_301")
        self.verticalLayout.addWidget(self.stepButton_301)
        self.stepButton_302 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_302.sizePolicy().hasHeightForWidth())
        self.stepButton_302.setSizePolicy(sizePolicy)
        self.stepButton_302.setObjectName("stepButton_302")
        self.verticalLayout.addWidget(self.stepButton_302)
        self.stepButton_303 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_303.sizePolicy().hasHeightForWidth())
        self.stepButton_303.setSizePolicy(sizePolicy)
        self.stepButton_303.setObjectName("stepButton_303")
        self.verticalLayout.addWidget(self.stepButton_303)
        self.stepButton_304 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_304.sizePolicy().hasHeightForWidth())
        self.stepButton_304.setSizePolicy(sizePolicy)
        self.stepButton_304.setObjectName("stepButton_304")
        self.verticalLayout.addWidget(self.stepButton_304)
        self.stepButton_305 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepButton_305.sizePolicy().hasHeightForWidth())
        self.stepButton_305.setSizePolicy(sizePolicy)
        self.stepButton_305.setObjectName("stepButton_305")
        self.verticalLayout.addWidget(self.stepButton_305)
        self.actionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.actionBox.setGeometry(QtCore.QRect(240, 10, 191, 811))
        self.actionBox.setObjectName("actionBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.actionBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 171, 781))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.actionButton_101 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_101.setCheckable(True)
        self.actionButton_101.setObjectName("actionButton_101")
        self.verticalLayout_2.addWidget(self.actionButton_101)
        self.actionButton_102 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_102.setCheckable(True)
        self.actionButton_102.setObjectName("actionButton_102")
        self.verticalLayout_2.addWidget(self.actionButton_102)
        self.actionButton_103 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_103.setCheckable(True)
        self.actionButton_103.setObjectName("actionButton_103")
        self.verticalLayout_2.addWidget(self.actionButton_103)
        self.actionButton_104 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_104.setCheckable(True)
        self.actionButton_104.setObjectName("actionButton_104")
        self.verticalLayout_2.addWidget(self.actionButton_104)
        self.actionButton_105 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_105.setCheckable(True)
        self.actionButton_105.setObjectName("actionButton_105")
        self.verticalLayout_2.addWidget(self.actionButton_105)
        self.actionButton_106 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_106.setCheckable(True)
        self.actionButton_106.setObjectName("actionButton_106")
        self.verticalLayout_2.addWidget(self.actionButton_106)
        self.actionButton_107 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_107.setObjectName("actionButton_107")
        self.verticalLayout_2.addWidget(self.actionButton_107)
        self.actionButton_108 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_108.setObjectName("actionButton_108")
        self.verticalLayout_2.addWidget(self.actionButton_108)
        self.actionButton_109 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_109.setObjectName("actionButton_109")
        self.verticalLayout_2.addWidget(self.actionButton_109)
        self.actionButton_110 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_110.setCheckable(False)
        self.actionButton_110.setChecked(False)
        self.actionButton_110.setObjectName("actionButton_110")
        self.verticalLayout_2.addWidget(self.actionButton_110)
        self.actionButton_111 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_111.setCheckable(True)
        self.actionButton_111.setObjectName("actionButton_111")
        self.verticalLayout_2.addWidget(self.actionButton_111)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.actionButton_201 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_201.setCheckable(True)
        self.actionButton_201.setObjectName("actionButton_201")
        self.verticalLayout_2.addWidget(self.actionButton_201)
        self.actionButton_202 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_202.setCheckable(True)
        self.actionButton_202.setObjectName("actionButton_202")
        self.verticalLayout_2.addWidget(self.actionButton_202)
        self.actionButton_203 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_203.setCheckable(True)
        self.actionButton_203.setObjectName("actionButton_203")
        self.verticalLayout_2.addWidget(self.actionButton_203)
        self.actionButton_204 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_204.setCheckable(True)
        self.actionButton_204.setObjectName("actionButton_204")
        self.verticalLayout_2.addWidget(self.actionButton_204)
        self.actionButton_205 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_205.setCheckable(True)
        self.actionButton_205.setObjectName("actionButton_205")
        self.verticalLayout_2.addWidget(self.actionButton_205)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.actionButton_301 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_301.setCheckable(True)
        self.actionButton_301.setObjectName("actionButton_301")
        self.verticalLayout_2.addWidget(self.actionButton_301)
        self.actionButton_302 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_302.setCheckable(True)
        self.actionButton_302.setObjectName("actionButton_302")
        self.verticalLayout_2.addWidget(self.actionButton_302)
        self.actionButton_303 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_303.setCheckable(True)
        self.actionButton_303.setObjectName("actionButton_303")
        self.verticalLayout_2.addWidget(self.actionButton_303)
        self.actionButton_304 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_304.setCheckable(True)
        self.actionButton_304.setObjectName("actionButton_304")
        self.verticalLayout_2.addWidget(self.actionButton_304)
        self.actionButton_305 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_305.setCheckable(True)
        self.actionButton_305.setObjectName("actionButton_305")
        self.verticalLayout_2.addWidget(self.actionButton_305)
        self.actionButton_306 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_306.setObjectName("actionButton_306")
        self.verticalLayout_2.addWidget(self.actionButton_306)
        self.actionButton_307 = QtWidgets.QPushButton(self.layoutWidget1)
        self.actionButton_307.setCheckable(True)
        self.actionButton_307.setObjectName("actionButton_307")
        self.verticalLayout_2.addWidget(self.actionButton_307)
        self.logBox = QtWidgets.QGroupBox(self.centralwidget)
        self.logBox.setGeometry(QtCore.QRect(460, 340, 341, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logBox.setFont(font)
        self.logBox.setObjectName("logBox")
        self.logTextEdit = QtWidgets.QPlainTextEdit(self.logBox)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 30, 321, 281))
        self.logTextEdit.setObjectName("logTextEdit")
        self.otherBox = QtWidgets.QGroupBox(self.centralwidget)
        self.otherBox.setGeometry(QtCore.QRect(460, 10, 191, 321))
        self.otherBox.setObjectName("otherBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.otherBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 173, 291))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.otherButton_001 = QtWidgets.QPushButton(self.layoutWidget2)
        self.otherButton_001.setObjectName("otherButton_001")
        self.verticalLayout_3.addWidget(self.otherButton_001)
        self.otherButton_002 = QtWidgets.QPushButton(self.layoutWidget2)
        self.otherButton_002.setObjectName("otherButton_002")
        self.verticalLayout_3.addWidget(self.otherButton_002)
        self.otherButton_003 = QtWidgets.QPushButton(self.layoutWidget2)
        self.otherButton_003.setObjectName("otherButton_003")
        self.verticalLayout_3.addWidget(self.otherButton_003)
        self.otherButton_004 = QtWidgets.QPushButton(self.layoutWidget2)
        self.otherButton_004.setObjectName("otherButton_004")
        self.verticalLayout_3.addWidget(self.otherButton_004)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.otherButton_005 = QtWidgets.QPushButton(self.layoutWidget2)
        self.otherButton_005.setFlat(False)
        self.otherButton_005.setObjectName("otherButton_005")
        self.verticalLayout_3.addWidget(self.otherButton_005)
        self.otherButton_006 = QtWidgets.QPushButton(self.layoutWidget2)
        self.otherButton_006.setObjectName("otherButton_006")
        self.verticalLayout_3.addWidget(self.otherButton_006)
        self.otherButton_007 = QtWidgets.QPushButton(self.layoutWidget2)
        self.otherButton_007.setObjectName("otherButton_007")
        self.verticalLayout_3.addWidget(self.otherButton_007)
        self.timerBox = QtWidgets.QGroupBox(self.centralwidget)
        self.timerBox.setGeometry(QtCore.QRect(460, 690, 341, 131))
        self.timerBox.setObjectName("timerBox")
        self.time_label = QtWidgets.QLabel(self.timerBox)
        self.time_label.setGeometry(QtCore.QRect(90, 40, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.time_label.setObjectName("time_label")
        self.upTimeButton = QtWidgets.QPushButton(self.timerBox)
        self.upTimeButton.setGeometry(QtCore.QRect(290, 30, 41, 41))
        self.upTimeButton.setObjectName("upTimeButton")
        self.downTimeButton = QtWidgets.QPushButton(self.timerBox)
        self.downTimeButton.setGeometry(QtCore.QRect(290, 80, 41, 41))
        self.downTimeButton.setObjectName("downTimeButton")
        self.time_limit_label = QtWidgets.QLabel(self.centralwidget)
        self.time_limit_label.setGeometry(QtCore.QRect(620, 820, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time_limit_label.setFont(font)
        self.time_limit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_limit_label.setOpenExternalLinks(False)
        self.time_limit_label.setObjectName("time_limit_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setStyleSheet("font: 10pt;")
        self.statusbar.setStyleSheet("font: 10pt;")
        self.setFixedSize(self.size())
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stepBox.setTitle(_translate("MainWindow", "Пропустить"))
        self.stepButton_001.setText(_translate("MainWindow", "Старт ♫"))
        self.stepButton_101.setText(_translate("MainWindow", "Тыкнуть зонтом"))
        self.stepButton_102.setText(_translate("MainWindow", "Повесить грибы"))
        self.stepButton_103.setText(_translate("MainWindow", "Надеть валенки"))
        self.stepButton_104.setText(_translate("MainWindow", "Надеть калоши"))
        self.stepButton_105.setText(_translate("MainWindow", "Мешочки в веретено"))
        self.stepButton_106.setText(_translate("MainWindow", "Веретено крутим"))
        self.stepButton_107.setText(_translate("MainWindow", "Надеть лапти"))
        self.stepButton_108.setText(_translate("MainWindow", "Яблоком по столу"))
        self.stepButton_109.setText(_translate("MainWindow", "Черепа выставить"))
        self.stepButton_110.setText(_translate("MainWindow", "Ступу разгадать"))
        self.stepButton_111.setText(_translate("MainWindow", "*Кнопки на печи ♫"))
        self.stepButton_201.setText(_translate("MainWindow", "*Ввод \"ступа\""))
        self.stepButton_202.setText(_translate("MainWindow", "*Ввод \"ижица\""))
        self.stepButton_203.setText(_translate("MainWindow", "*Прилетели ♫"))
        self.stepButton_301.setText(_translate("MainWindow", "Решить головоломку"))
        self.stepButton_302.setText(_translate("MainWindow", "*Поставить сундук"))
        self.stepButton_303.setText(_translate("MainWindow", "Убить зайца"))
        self.stepButton_304.setText(_translate("MainWindow", "Убить всех зайцев"))
        self.stepButton_305.setText(_translate("MainWindow", "*Яйцо поставили"))
        self.actionBox.setTitle(_translate("MainWindow", "Сделать"))
        self.actionButton_101.setText(_translate("MainWindow", "Грибы уронить"))
        self.actionButton_102.setText(_translate("MainWindow", "Холодильник откр."))
        self.actionButton_103.setText(_translate("MainWindow", "Полено в.стена откр."))
        self.actionButton_104.setText(_translate("MainWindow", "Полено н.стена откр."))
        self.actionButton_105.setText(_translate("MainWindow", "Полено в печи откр."))
        self.actionButton_106.setText(_translate("MainWindow", "Окно откр."))
        self.actionButton_107.setText(_translate("MainWindow", "Окно \"зима\""))
        self.actionButton_108.setText(_translate("MainWindow", "Окно \"весна\""))
        self.actionButton_109.setText(_translate("MainWindow", "Окно \"лето\""))
        self.actionButton_110.setText(_translate("MainWindow", "Подсказка черепа"))
        self.actionButton_111.setText(_translate("MainWindow", "Печь откр."))
        self.actionButton_201.setText(_translate("MainWindow", "Л.голова поднять"))
        self.actionButton_202.setText(_translate("MainWindow", "Л.голова опустить"))
        self.actionButton_203.setText(_translate("MainWindow", "П.голова поднять"))
        self.actionButton_204.setText(_translate("MainWindow", "П.голова опустить"))
        self.actionButton_205.setText(_translate("MainWindow", "Проход откр."))
        self.actionButton_301.setText(_translate("MainWindow", "Решетка откр."))
        self.actionButton_302.setText(_translate("MainWindow", "Решетка закр."))
        self.actionButton_303.setText(_translate("MainWindow", "Утка откр."))
        self.actionButton_304.setText(_translate("MainWindow", "Яйцо вверх (яйцо)"))
        self.actionButton_305.setText(_translate("MainWindow", "Яйцо вниз (игла)"))
        self.actionButton_306.setText(_translate("MainWindow", "Яйцо дверца откр."))
        self.actionButton_307.setText(_translate("MainWindow", "Откр. Выход"))
        self.logBox.setTitle(_translate("MainWindow", "События"))
        self.otherBox.setTitle(_translate("MainWindow", "Общее"))
        self.otherButton_001.setText(_translate("MainWindow", "Перезагрузка"))
        self.otherButton_002.setText(_translate("MainWindow", "Ресет ПК \"Голов-ка\""))
        self.otherButton_003.setText(_translate("MainWindow", "Ресет ПК \"Окно\""))
        self.otherButton_004.setText(_translate("MainWindow", "Ресет ПК \"Яблоко\""))
        self.otherButton_005.setText(_translate("MainWindow", "Старт с Комнаты 1"))
        self.otherButton_006.setText(_translate("MainWindow", "Старт с Комнаты 2"))
        self.otherButton_007.setText(_translate("MainWindow", "Старт с Комнаты 3"))
        self.timerBox.setTitle(_translate("MainWindow", "Таймер"))
        self.time_label.setText(_translate("MainWindow", "00:00"))
        self.upTimeButton.setText(_translate("MainWindow", "+"))
        self.downTimeButton.setText(_translate("MainWindow", "-"))
        self.time_limit_label.setText(_translate("MainWindow", "Предельное время игры: 60 мин."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

